### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by ashifolfi** [chicken-with-lips/rmlui.net#1]
This code is lacking a license. This makes it completely unclear what is an isn't allowed to be done with this code which will hurt the chances of anyone contributing to this project or trying to use it.

I suggest you add the MIT license. It's a permissive license that a lot of large projects use (such as RmlUi itself) and would do fine for this library in my honest opinion.

**Comment by iainmckay** [comment]
I've added a license. Cheers.
